---
- name: Create the sockpuppet group
  group:
    name: "{{ sockpuppet_system_group }}"
    state: present
    system: true

- name: Create the sockpuppet user
  user:
    name: "{{ sockpuppet_system_user }}"
    groups: "{{ sockpuppet_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
