---

- name: install dependencies
  package:
    name: "{{ item }}"
  become: true
  with_items:
    - python-virtualenv
    - git
    - gcc

- name: Install sockpuppet into virtualenv
  pip:
    name: git+https://github.com/stackhpc/sockpuppet
    virtualenv: "{{ sockpuppet_virtualenv_path }}"
  become: true
