---

- name: Determine which variable overrides exist
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ ansible_os_family | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
  regsiter: stat_result
  tags:
    - sockpuppet_install
    - sockpuppet_configure
    - sockpuppet_run

- name: Gather variables for each operating system
  include_vars: "{{ item.module_args.path }}"
  when: "{{ item.exists }}"
  with_items: stat_result
  tags:
    - sockpuppet_install
    - sockpuppet_configure
    - sockpuppet_run

- import_tasks: preflight.yml
  tags:
    - sockpuppet_install
    - sockpuppet_configure
    - sockpuppet_run

- import_tasks: install.yml
  become: true
  when: (not __sockpuppet_is_installed.stat.exists) or (__sockpuppet_current_version_output.stderr_lines[0].split(" ")[1] != sockpuppet_version)
  tags:
    - sockpuppet_install

- import_tasks: configure.yml
  become: true
  tags:
    - sockpuppet_configure

- name: Ensure sockpuppet is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: sockpuppet
    enabled: true
  tags:
    - sockpuppet_run
